"""init

Revision ID: d949b28e7576
Revises: 
Create Date: 2026-05-29 14:08:04.948426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd949b28e7576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('private', 'group', 'supergroup', 'channel', 'saved', 'secret', name='chattype'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('public_username', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('pinned_message_id', sa.Integer(), nullable=True),
    sa.Column('linked_chat_id', sa.Integer(), nullable=True),
    sa.Column('is_forum', sa.Boolean(), nullable=False),
    sa.Column('slow_mode_seconds', sa.Integer(), nullable=False),
    sa.Column('is_history_visible', sa.Boolean(), nullable=False),
    sa.Column('is_join_by_request', sa.Boolean(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_send_media', sa.Boolean(), nullable=False),
    sa.Column('can_send_polls', sa.Boolean(), nullable=False),
    sa.Column('can_add_users', sa.Boolean(), nullable=False),
    sa.Column('can_pin_messages', sa.Boolean(), nullable=False),
    sa.Column('can_change_info', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_public_username'), ['public_username'], unique=True)
        batch_op.create_index(batch_op.f('ix_chats_type'), ['type'], unique=False)

    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hashtags_tag'), ['tag'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birthday', sa.DateTime(timezone=True), nullable=True),
    sa.Column('personal_channel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personal_channel_id'], ['chats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('away_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.String(length=32), nullable=False),
    sa.Column('custom_schedule', sa.JSON(), nullable=True),
    sa.Column('only_for_contacts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocks_pair')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('api_token', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('about', sa.String(length=120), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('supports_inline', sa.Boolean(), nullable=False),
    sa.Column('inline_placeholder', sa.String(length=64), nullable=True),
    sa.Column('can_join_groups', sa.Boolean(), nullable=False),
    sa.Column('can_read_all_group_messages', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_api_token'), ['api_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_bots_owner_id'), ['owner_id'], unique=False)

    op.create_table('business_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=True),
    sa.Column('location_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('chat_link_text', sa.String(length=80), nullable=True),
    sa.Column('intro_title', sa.String(length=80), nullable=True),
    sa.Column('intro_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('audio', 'video', name='calltype'), nullable=False),
    sa.Column('status', sa.Enum('ringing', 'accepted', 'declined', 'missed', 'ended', name='callstatus'), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('end_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_initiator_id'), ['initiator_id'], unique=False)

    op.create_table('chat_admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('member_promoted', 'member_demoted', 'member_kicked', 'member_banned', 'member_unbanned', 'member_invited', 'member_joined', 'member_left', 'member_restricted', 'title_changed', 'description_changed', 'photo_changed', 'photo_removed', 'username_changed', 'permissions_changed', 'message_pinned', 'message_unpinned', 'message_deleted', 'message_edited', 'invite_created', 'invite_revoked', 'slow_mode_changed', 'history_visibility_changed', 'topic_created', 'topic_edited', 'topic_closed', 'topic_deleted', 'linked_chat_changed', name='chatadminaction'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_admin_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_admin_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_admin_log_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_admin_log_created_at'), ['created_at'], unique=False)

    op.create_table('chat_admin_rights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_change_info', sa.Boolean(), nullable=False),
    sa.Column('can_delete_messages', sa.Boolean(), nullable=False),
    sa.Column('can_ban_users', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_pin_messages', sa.Boolean(), nullable=False),
    sa.Column('can_promote_members', sa.Boolean(), nullable=False),
    sa.Column('can_manage_video_chats', sa.Boolean(), nullable=False),
    sa.Column('can_post_messages', sa.Boolean(), nullable=False),
    sa.Column('can_edit_messages', sa.Boolean(), nullable=False),
    sa.Column('can_manage_topics', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_admin_rights_pair')
    )
    with op.batch_alter_table('chat_admin_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_admin_rights_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_admin_rights_user_id'), ['user_id'], unique=False)

    op.create_table('chat_banned_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'word', name='uq_chat_banned_words_unique')
    )
    with op.batch_alter_table('chat_banned_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_banned_words_chat_id'), ['chat_id'], unique=False)

    op.create_table('chat_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('include_contacts', sa.Boolean(), nullable=False),
    sa.Column('include_non_contacts', sa.Boolean(), nullable=False),
    sa.Column('include_groups', sa.Boolean(), nullable=False),
    sa.Column('include_channels', sa.Boolean(), nullable=False),
    sa.Column('include_bots', sa.Boolean(), nullable=False),
    sa.Column('exclude_muted', sa.Boolean(), nullable=False),
    sa.Column('exclude_read', sa.Boolean(), nullable=False),
    sa.Column('exclude_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_folders_user_id'), ['user_id'], unique=False)

    op.create_table('chat_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('member_limit', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_invites_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_invites_code'), ['code'], unique=True)

    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('creator', 'admin', 'member', 'restricted', 'left', 'banned', name='chatmemberrole'), nullable=False),
    sa.Column('custom_title', sa.String(length=50), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('mute_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('unread_mentions_count', sa.Integer(), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_send_media', sa.Boolean(), nullable=False),
    sa.Column('restricted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_members_pair')
    )
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_members_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_members_user_id'), ['user_id'], unique=False)

    op.create_table('chat_mute_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('mute_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_previews', sa.Boolean(), nullable=False),
    sa.Column('sound', sa.String(length=50), nullable=True),
    sa.Column('only_mentions', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_chat_mute_settings_pair')
    )
    with op.batch_alter_table('chat_mute_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_mute_settings_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_mute_settings_user_id'), ['user_id'], unique=False)

    op.create_table('chat_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('icon_color', sa.String(length=16), nullable=True),
    sa.Column('icon_emoji', sa.String(length=16), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_topics_chat_id'), ['chat_id'], unique=False)

    op.create_table('close_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'friend_id', name='uq_close_friends_pair')
    )
    with op.batch_alter_table('close_friends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_close_friends_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_close_friends_owner_id'), ['owner_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('custom_first_name', sa.String(length=80), nullable=True),
    sa.Column('custom_last_name', sa.String(length=80), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'contact_id', name='uq_contacts_owner_contact')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)

    op.create_table('greeting_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('no_activity_days', sa.Integer(), nullable=False),
    sa.Column('only_for_non_contacts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'register', 'password_reset', 'phone_change', 'email_change', name='otppurpose'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_user_id'), ['user_id'], unique=False)

    op.create_table('privacy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('profile_photo', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('phone_number', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('forwards', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('calls', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('groups_invite', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('birthday', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.Column('bio', sa.Enum('everybody', 'contacts', 'nobody', name='privacylevel'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('quick_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shortcut', name='uq_quick_replies_unique')
    )
    with op.batch_alter_table('quick_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_replies_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.Enum('user', 'message', 'chat', 'story', name='reporttargettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('spam', 'violence', 'pornography', 'child_abuse', 'drugs', 'personal_data', 'fake_account', 'copyright', 'illegal', 'other', name='reportreason'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_type'), ['target_type'], unique=False)

    op.create_table('secret_chat_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('rekey_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_secret_chat_keys_pair')
    )
    with op.batch_alter_table('secret_chat_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_chat_keys_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_chat_keys_user_id'), ['user_id'], unique=False)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('privacy', sa.Enum('everybody', 'contacts', 'close_friends', 'selected', name='storyprivacytype'), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=True),
    sa.Column('excluded_user_ids', sa.JSON(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('allow_replies', sa.Boolean(), nullable=False),
    sa.Column('allow_reactions', sa.Boolean(), nullable=False),
    sa.Column('allow_forwards', sa.Boolean(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('reactions_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_expires_at'), ['expires_at'], unique=False)

    op.create_table('two_factor_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.String(length=150), nullable=True),
    sa.Column('recovery_email', sa.String(length=255), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_avatars_user_id'), ['user_id'], unique=False)

    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('web', 'android', 'ios', 'desktop', name='deviceplatform'), nullable=False),
    sa.Column('push_token', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_token')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_user_id'), ['user_id'], unique=False)

    op.create_table('user_geo_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_geo_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_geo_index_expires_at'), ['expires_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('web', 'android', 'ios', 'desktop', name='deviceplatform'), nullable=False),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token'), ['refresh_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('username_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('username_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_username_history_user_id'), ['user_id'], unique=False)

    op.create_table('bot_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'command', 'scope', 'chat_id', name='uq_bot_commands_unique')
    )
    with op.batch_alter_table('bot_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_commands_bot_id'), ['bot_id'], unique=False)

    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_minute', sa.Integer(), nullable=False),
    sa.Column('close_minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_hours_business_id'), ['business_id'], unique=False)

    op.create_table('call_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_video_on', sa.Boolean(), nullable=False),
    sa.Column('is_screen_sharing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'user_id', name='uq_call_participants_pair')
    )
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_participants_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_participants_user_id'), ['user_id'], unique=False)

    op.create_table('chat_folder_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['chat_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'chat_id', name='uq_chat_folder_items_pair')
    )
    with op.batch_alter_table('chat_folder_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_folder_items_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_folder_items_folder_id'), ['folder_id'], unique=False)

    op.create_table('chat_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invite_id'], ['chat_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_join_requests_pair')
    )
    with op.batch_alter_table('chat_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_join_requests_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_join_requests_user_id'), ['user_id'], unique=False)

    op.create_table('inline_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('offset', sa.String(length=64), nullable=True),
    sa.Column('chat_type', sa.String(length=20), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inline_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inline_queries_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inline_queries_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('text', 'photo', 'video', 'video_note', 'animation', 'audio', 'voice', 'file', 'location', 'live_location', 'contact', 'poll', 'call', 'story_reply', 'bot_inline', 'system', name='messagetype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('thread_root_id', sa.Integer(), nullable=True),
    sa.Column('reply_quote_text', sa.Text(), nullable=True),
    sa.Column('reply_quote_offset', sa.Integer(), nullable=True),
    sa.Column('reply_quote_entities', sa.JSON(), nullable=True),
    sa.Column('reply_markup', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(length=8), nullable=True),
    sa.Column('forward_from_user_id', sa.Integer(), nullable=True),
    sa.Column('forward_from_chat_id', sa.Integer(), nullable=True),
    sa.Column('forward_from_message_id', sa.Integer(), nullable=True),
    sa.Column('forward_sender_name', sa.String(length=150), nullable=True),
    sa.Column('forward_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_silent', sa.Boolean(), nullable=False),
    sa.Column('is_via_bot', sa.Boolean(), nullable=False),
    sa.Column('via_bot_id', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('forwards_count', sa.Integer(), nullable=False),
    sa.Column('self_destruct_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forward_from_chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forward_from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_root_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['chat_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['via_bot_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_chat_created', ['chat_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_root_id'), ['thread_root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_topic_id'), ['topic_id'], unique=False)

    op.create_table('story_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_id', name='uq_story_reactions_pair')
    )
    with op.batch_alter_table('story_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_reactions_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('story_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_id', name='uq_story_views_pair')
    )
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_views_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_views_user_id'), ['user_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('waveform', sa.JSON(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('has_spoiler', sa.Boolean(), nullable=False),
    sa.Column('is_view_once', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('callback_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('chat_instance', sa.String(length=64), nullable=True),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.String(length=200), nullable=True),
    sa.Column('answer_show_alert', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('callback_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callback_queries_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callback_queries_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callback_queries_user_id'), ['user_id'], unique=False)

    op.create_table('message_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('vcard', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('message_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['chat_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_drafts_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_drafts_user_id'), ['user_id'], unique=False)

    op.create_table('message_edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_edit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_edit_history_message_id'), ['message_id'], unique=False)

    op.create_table('message_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'hashtag_id', name='uq_message_hashtags_pair')
    )
    with op.batch_alter_table('message_hashtags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_hashtags_hashtag_id'), ['hashtag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_hashtags_message_id'), ['message_id'], unique=False)

    op.create_table('message_link_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_link_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_link_previews_message_id'), ['message_id'], unique=False)

    op.create_table('message_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('live_period_seconds', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Integer(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('message_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_mentions_mentioned_user_id'), ['mentioned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_mentions_message_id'), ['message_id'], unique=False)

    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('is_big', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_reactions_unique')
    )
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('message_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_reads_pair')
    )
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reads_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reads_user_id'), ['user_id'], unique=False)

    op.create_table('message_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_views_pair')
    )
    with op.batch_alter_table('message_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_views_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_views_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('pinned_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('pinned_by_id', sa.Integer(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_pinned_messages_pair')
    )
    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pinned_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pinned_messages_message_id'), ['message_id'], unique=False)

    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('allows_multiple_answers', sa.Boolean(), nullable=False),
    sa.Column('is_quiz', sa.Boolean(), nullable=False),
    sa.Column('correct_option_id', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=150), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('voter_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_options_poll_id'), ['poll_id'], unique=False)

    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'option_id', 'user_id', name='uq_poll_votes_unique')
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_votes_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_poll_votes_poll_id'))
        batch_op.drop_index(batch_op.f('ix_poll_votes_option_id'))

    op.drop_table('poll_votes')
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_options_poll_id'))

    op.drop_table('poll_options')
    op.drop_table('polls')
    with op.batch_alter_table('pinned_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pinned_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_pinned_messages_chat_id'))

    op.drop_table('pinned_messages')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('message_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_views_message_id'))

    op.drop_table('message_views')
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reads_message_id'))

    op.drop_table('message_reads')
    with op.batch_alter_table('message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reactions_message_id'))

    op.drop_table('message_reactions')
    with op.batch_alter_table('message_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_mentions_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_mentions_mentioned_user_id'))

    op.drop_table('message_mentions')
    op.drop_table('message_locations')
    with op.batch_alter_table('message_link_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_link_previews_message_id'))

    op.drop_table('message_link_previews')
    with op.batch_alter_table('message_hashtags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_hashtags_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_hashtags_hashtag_id'))

    op.drop_table('message_hashtags')
    with op.batch_alter_table('message_edit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_edit_history_message_id'))

    op.drop_table('message_edit_history')
    with op.batch_alter_table('message_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_drafts_chat_id'))

    op.drop_table('message_drafts')
    op.drop_table('message_contacts')
    with op.batch_alter_table('callback_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callback_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_callback_queries_message_id'))
        batch_op.drop_index(batch_op.f('ix_callback_queries_bot_id'))

    op.drop_table('callback_queries')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_message_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_story_views_story_id'))

    op.drop_table('story_views')
    with op.batch_alter_table('story_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_story_reactions_story_id'))

    op.drop_table('story_reactions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_topic_id'))
        batch_op.drop_index(batch_op.f('ix_messages_thread_root_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_messages_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))
        batch_op.drop_index('ix_messages_chat_created')

    op.drop_table('messages')
    with op.batch_alter_table('inline_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inline_queries_user_id'))
        batch_op.drop_index(batch_op.f('ix_inline_queries_bot_id'))

    op.drop_table('inline_queries')
    with op.batch_alter_table('chat_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_join_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_join_requests_chat_id'))

    op.drop_table('chat_join_requests')
    with op.batch_alter_table('chat_folder_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_folder_items_folder_id'))
        batch_op.drop_index(batch_op.f('ix_chat_folder_items_chat_id'))

    op.drop_table('chat_folder_items')
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_participants_call_id'))

    op.drop_table('call_participants')
    with op.batch_alter_table('business_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_hours_business_id'))

    op.drop_table('business_hours')
    with op.batch_alter_table('bot_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_commands_bot_id'))

    op.drop_table('bot_commands')
    with op.batch_alter_table('username_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_username_history_user_id'))

    op.drop_table('username_history')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_geo_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_geo_index_expires_at'))

    op.drop_table('user_geo_index')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_user_id'))

    op.drop_table('user_devices')
    with op.batch_alter_table('user_avatars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatars_user_id'))

    op.drop_table('user_avatars')
    op.drop_table('two_factor_auth')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_expires_at'))
        batch_op.drop_index(batch_op.f('ix_stories_created_at'))
        batch_op.drop_index(batch_op.f('ix_stories_chat_id'))
        batch_op.drop_index(batch_op.f('ix_stories_author_id'))

    op.drop_table('stories')
    with op.batch_alter_table('secret_chat_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_chat_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_secret_chat_keys_chat_id'))

    op.drop_table('secret_chat_keys')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_target_type'))
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    with op.batch_alter_table('quick_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_replies_user_id'))

    op.drop_table('quick_replies')
    op.drop_table('privacy_settings')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_identifier'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_user_id'))

    op.drop_table('login_attempts')
    op.drop_table('greeting_messages')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_contact_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('close_friends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_close_friends_owner_id'))
        batch_op.drop_index(batch_op.f('ix_close_friends_friend_id'))

    op.drop_table('close_friends')
    with op.batch_alter_table('chat_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_topics_chat_id'))

    op.drop_table('chat_topics')
    with op.batch_alter_table('chat_mute_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_mute_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_mute_settings_chat_id'))

    op.drop_table('chat_mute_settings')
    with op.batch_alter_table('chat_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_members_chat_id'))

    op.drop_table('chat_members')
    with op.batch_alter_table('chat_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_invites_code'))
        batch_op.drop_index(batch_op.f('ix_chat_invites_chat_id'))

    op.drop_table('chat_invites')
    with op.batch_alter_table('chat_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_folders_user_id'))

    op.drop_table('chat_folders')
    with op.batch_alter_table('chat_banned_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_banned_words_chat_id'))

    op.drop_table('chat_banned_words')
    with op.batch_alter_table('chat_admin_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_admin_rights_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_admin_rights_chat_id'))

    op.drop_table('chat_admin_rights')
    with op.batch_alter_table('chat_admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_admin_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_admin_log_chat_id'))
        batch_op.drop_index(batch_op.f('ix_chat_admin_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_chat_admin_log_action'))

    op.drop_table('chat_admin_log')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_initiator_id'))
        batch_op.drop_index(batch_op.f('ix_calls_chat_id'))

    op.drop_table('calls')
    op.drop_table('business_accounts')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_owner_id'))
        batch_op.drop_index(batch_op.f('ix_bots_api_token'))

    op.drop_table('bots')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_blocked_id'))

    op.drop_table('blocks')
    op.drop_table('away_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hashtags_tag'))

    op.drop_table('hashtags')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_type'))
        batch_op.drop_index(batch_op.f('ix_chats_public_username'))

    op.drop_table('chats')
    # ### end Alembic commands ###
